//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationPollingDates
    {
        public int Id { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<System.DateTime> ElectionStartDate { get; set; }
        public Nullable<System.DateTime> ElectionEndDate { get; set; }
    }
}
