//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mail()
        {
            this.MailError = new HashSet<MailError>();
        }
    
        public int id { get; set; }
        public int MailTo { get; set; }
        public string MailContent { get; set; }
        public string MailSubject { get; set; }
        public int MailFrom { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual MailStatus MailStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailError> MailError { get; set; }
    }
}
