//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollingClerk
    {
        public int Id { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> AssociateMember { get; set; }
        public Nullable<int> AssociateMemberSecondary { get; set; }
    }
}
