//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePassenger
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string TCK { get; set; }
        public string Phone { get; set; }
        public int PassengerCount { get; set; }
        public int AddUserId { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
