//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoterInfo()
        {
            this.VoterContact = new HashSet<VoterContact>();
            this.VoterRegisteredCity = new HashSet<VoterRegisteredCity>();
        }
    
        public int Id { get; set; }
        public string ForeignNumber { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string BirthCity { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string RegisteredCity { get; set; }
        public string RegisteredDistrict { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoterContact> VoterContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoterRegisteredCity> VoterRegisteredCity { get; set; }
    }
}
