//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterContact
    {
        public int Id { get; set; }
        public Nullable<int> VoterId { get; set; }
        public string FormatedAddress { get; set; }
        public string Street { get; set; }
        public string Street_Number { get; set; }
        public string PostCode { get; set; }
        public string ApartmentNumber { get; set; }
        public string Route { get; set; }
        public string Locality { get; set; }
        public string Administrative_Level1 { get; set; }
        public string Administrative_Level2 { get; set; }
        public string Administrative_Level3 { get; set; }
        public string Administrative_Level4 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Country { get; set; }
        public string ISO { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsProcess { get; set; }
        public string ResultText { get; set; }
    
        public virtual VoterInfo VoterInfo { get; set; }
    }
}
