//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCarSearchQuery
    {
        public long Id { get; set; }
        public string PostalCode { get; set; }
        public string CityName { get; set; }
        public string SearchText { get; set; }
    }
}
