//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCarList
    {
        public int Id { get; set; }
        public string CarType { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public int Qutoa { get; set; }
        public string CountryName { get; set; }
        public string PostalCode { get; set; }
        public string CityName { get; set; }
        public string ResponsibleName { get; set; }
        public string ResponsiblePhone { get; set; }
        public Nullable<int> Destination { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public string DepartureHour { get; set; }
        public string DestinationBox { get; set; }
        public int PassengerCount { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<bool> IsVoluntaryService { get; set; }
    }
}
