//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secimyolu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPollingBox
    {
        public int Id { get; set; }
        public string BoxNumber { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<System.DateTime> PollingDate { get; set; }
        public string Member { get; set; }
        public string MemberNameSurname { get; set; }
        public string MemberSecondary { get; set; }
        public string MemberSecondaryNameSurname { get; set; }
    }
}
